//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: transfer_hook
// ----------------------------------------------------------------------------
pub mod transfer_hook {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for transfer_hook
    pub fn program_id() -> Pubkey {
        pubkey!("FtPdSNiQ8ieM4yE1V8FekUk7WDbgZrx9ehb3CyaXzHtG")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: Execute
    // ....................................................................

    /// Main instruction struct for Execute
    pub struct ExecuteInstruction {
        pub accounts: ExecuteInstructionAccountMetas,
        pub data: ExecuteInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Execute instruction
    #[derive(Debug, Clone, Default)]
    pub struct ExecuteInstructionAccountMetas {
        pub source_token_account: AccountMeta,

        pub mint: AccountMeta,

        pub destination_token_account: AccountMeta,

        pub source_authority: AccountMeta,

        pub extra_account_meta_list: AccountMeta,

        pub source_blacklist_entry: AccountMeta,

        pub destination_blacklist_entry: AccountMeta,

        pub stc_program_id: AccountMeta,
    }

    /// Account pubkeys for Execute instruction
    #[derive(Debug, Clone)]
    pub struct ExecuteInstructionAccounts {
        pub source_token_account: Pubkey,

        pub mint: Pubkey,

        pub destination_token_account: Pubkey,

        pub source_authority: Pubkey,

        pub extra_account_meta_list: Pubkey,

        pub source_blacklist_entry: Pubkey,

        pub destination_blacklist_entry: Pubkey,
    }

    impl ExecuteInstructionAccounts {
        pub fn new(
            source_token_account: Pubkey,

            mint: Pubkey,

            destination_token_account: Pubkey,

            source_authority: Pubkey,

            extra_account_meta_list: Pubkey,

            source_blacklist_entry: Pubkey,

            destination_blacklist_entry: Pubkey,
        ) -> Self {
            Self {
                source_token_account,

                mint,

                destination_token_account,

                source_authority,

                extra_account_meta_list,

                source_blacklist_entry,

                destination_blacklist_entry,
            }
        }
    }

    /// Instruction data for Execute
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ExecuteInstructionData {
        pub amount: u64,
    }

    impl ExecuteInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for ExecuteInstruction
    impl ExecuteInstruction {
        fn discriminator() -> [u8; 8] {
            [130u8, 221u8, 242u8, 154u8, 13u8, 193u8, 189u8, 29u8]
        }

        pub fn data(data: ExecuteInstructionData) -> Self {
            Self {
                accounts: ExecuteInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ExecuteInstructionAccounts) -> Self {
            self.accounts.source_token_account =
                AccountMeta::new_readonly(accounts.source_token_account, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.destination_token_account =
                AccountMeta::new_readonly(accounts.destination_token_account, false);

            self.accounts.source_authority =
                AccountMeta::new_readonly(accounts.source_authority, false);

            self.accounts.extra_account_meta_list =
                AccountMeta::new_readonly(accounts.extra_account_meta_list, false);

            self.accounts.source_blacklist_entry =
                AccountMeta::new_readonly(accounts.source_blacklist_entry, false);

            self.accounts.destination_blacklist_entry =
                AccountMeta::new_readonly(accounts.destination_blacklist_entry, false);

            self.accounts.stc_program_id = AccountMeta::new_readonly(
                pubkey!("3nqtxhZZdpV5W2TPaa1hbWbeM3bhhsMg3Fy9oLdAHKfH"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.source_token_account.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.destination_token_account.clone());

            metas.push(self.accounts.source_authority.clone());

            metas.push(self.accounts.extra_account_meta_list.clone());

            metas.push(self.accounts.source_blacklist_entry.clone());

            metas.push(self.accounts.destination_blacklist_entry.clone());

            metas.push(self.accounts.stc_program_id.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitializeExtraAccountMetaList
    // ....................................................................

    /// Main instruction struct for InitializeExtraAccountMetaList
    pub struct InitializeExtraAccountMetaListInstruction {
        pub accounts: InitializeExtraAccountMetaListInstructionAccountMetas,
        pub data: InitializeExtraAccountMetaListInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeExtraAccountMetaList instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeExtraAccountMetaListInstructionAccountMetas {
        pub payer: AccountMeta,

        pub extra_account_meta_list: AccountMeta,

        pub mint: AccountMeta,

        pub stc_program_id: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeExtraAccountMetaList instruction
    #[derive(Debug, Clone)]
    pub struct InitializeExtraAccountMetaListInstructionAccounts {
        pub payer: Pubkey,

        pub extra_account_meta_list: Pubkey,

        pub mint: Pubkey,
    }

    impl InitializeExtraAccountMetaListInstructionAccounts {
        pub fn new(payer: Pubkey, extra_account_meta_list: Pubkey, mint: Pubkey) -> Self {
            Self {
                payer,

                extra_account_meta_list,

                mint,
            }
        }
    }

    /// Instruction data for InitializeExtraAccountMetaList
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeExtraAccountMetaListInstructionData {}

    impl InitializeExtraAccountMetaListInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for InitializeExtraAccountMetaListInstruction
    impl InitializeExtraAccountMetaListInstruction {
        fn discriminator() -> [u8; 8] {
            [92u8, 197u8, 174u8, 197u8, 41u8, 124u8, 19u8, 3u8]
        }

        pub fn data(data: InitializeExtraAccountMetaListInstructionData) -> Self {
            Self {
                accounts: InitializeExtraAccountMetaListInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(
            mut self,
            accounts: InitializeExtraAccountMetaListInstructionAccounts,
        ) -> Self {
            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.extra_account_meta_list =
                AccountMeta::new(accounts.extra_account_meta_list, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.stc_program_id = AccountMeta::new_readonly(
                pubkey!("3nqtxhZZdpV5W2TPaa1hbWbeM3bhhsMg3Fy9oLdAHKfH"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.extra_account_meta_list.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.stc_program_id.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ----------------------------------------------------------------------------
// Program: stc_program
// ----------------------------------------------------------------------------
pub mod stc_program {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for stc_program
    pub fn program_id() -> Pubkey {
        pubkey!("3nqtxhZZdpV5W2TPaa1hbWbeM3bhhsMg3Fy9oLdAHKfH")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: AddToBlacklist
    // ....................................................................

    /// Main instruction struct for AddToBlacklist
    pub struct AddToBlacklistInstruction {
        pub accounts: AddToBlacklistInstructionAccountMetas,
        pub data: AddToBlacklistInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AddToBlacklist instruction
    #[derive(Debug, Clone, Default)]
    pub struct AddToBlacklistInstructionAccountMetas {
        pub blacklister: AccountMeta,

        pub config: AccountMeta,

        pub role_account: AccountMeta,

        pub address_to_blacklist: AccountMeta,

        pub blacklist_entry: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for AddToBlacklist instruction
    #[derive(Debug, Clone)]
    pub struct AddToBlacklistInstructionAccounts {
        pub blacklister: Pubkey,

        pub config: Pubkey,

        pub role_account: Pubkey,

        pub address_to_blacklist: Pubkey,

        pub blacklist_entry: Pubkey,
    }

    impl AddToBlacklistInstructionAccounts {
        pub fn new(
            blacklister: Pubkey,

            config: Pubkey,

            role_account: Pubkey,

            address_to_blacklist: Pubkey,

            blacklist_entry: Pubkey,
        ) -> Self {
            Self {
                blacklister,

                config,

                role_account,

                address_to_blacklist,

                blacklist_entry,
            }
        }
    }

    /// Instruction data for AddToBlacklist
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AddToBlacklistInstructionData {}

    impl AddToBlacklistInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for AddToBlacklistInstruction
    impl AddToBlacklistInstruction {
        fn discriminator() -> [u8; 8] {
            [90u8, 115u8, 98u8, 231u8, 173u8, 119u8, 117u8, 176u8]
        }

        pub fn data(data: AddToBlacklistInstructionData) -> Self {
            Self {
                accounts: AddToBlacklistInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AddToBlacklistInstructionAccounts) -> Self {
            self.accounts.blacklister = AccountMeta::new(accounts.blacklister, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.role_account = AccountMeta::new_readonly(accounts.role_account, false);

            self.accounts.address_to_blacklist =
                AccountMeta::new_readonly(accounts.address_to_blacklist, false);

            self.accounts.blacklist_entry = AccountMeta::new(accounts.blacklist_entry, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.blacklister.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_account.clone());

            metas.push(self.accounts.address_to_blacklist.clone());

            metas.push(self.accounts.blacklist_entry.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Burn
    // ....................................................................

    /// Main instruction struct for Burn
    pub struct BurnInstruction {
        pub accounts: BurnInstructionAccountMetas,
        pub data: BurnInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Burn instruction
    #[derive(Debug, Clone, Default)]
    pub struct BurnInstructionAccountMetas {
        pub burner: AccountMeta,

        pub config: AccountMeta,

        pub role_account: AccountMeta,

        pub mint: AccountMeta,

        pub token_account: AccountMeta,

        pub token_account_owner: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Burn instruction
    #[derive(Debug, Clone)]
    pub struct BurnInstructionAccounts {
        pub burner: Pubkey,

        pub config: Pubkey,

        pub role_account: Pubkey,

        pub mint: Pubkey,

        pub token_account: Pubkey,

        pub token_account_owner: Pubkey,

        pub token_program: Pubkey,
    }

    impl BurnInstructionAccounts {
        pub fn new(
            burner: Pubkey,

            config: Pubkey,

            role_account: Pubkey,

            mint: Pubkey,

            token_account: Pubkey,

            token_account_owner: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                burner,

                config,

                role_account,

                mint,

                token_account,

                token_account_owner,

                token_program,
            }
        }
    }

    /// Instruction data for Burn
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct BurnInstructionData {
        pub amount: u64,
    }

    impl BurnInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for BurnInstruction
    impl BurnInstruction {
        fn discriminator() -> [u8; 8] {
            [116u8, 110u8, 29u8, 56u8, 107u8, 219u8, 42u8, 93u8]
        }

        pub fn data(data: BurnInstructionData) -> Self {
            Self {
                accounts: BurnInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: BurnInstructionAccounts) -> Self {
            self.accounts.burner = AccountMeta::new(accounts.burner, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.role_account = AccountMeta::new_readonly(accounts.role_account, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.token_account = AccountMeta::new(accounts.token_account, false);

            self.accounts.token_account_owner =
                AccountMeta::new_readonly(accounts.token_account_owner, true);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.burner.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_account.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_account.clone());

            metas.push(self.accounts.token_account_owner.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: FreezeAccount
    // ....................................................................

    /// Main instruction struct for FreezeAccount
    pub struct FreezeAccountInstruction {
        pub accounts: FreezeAccountInstructionAccountMetas,
        pub data: FreezeAccountInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for FreezeAccount instruction
    #[derive(Debug, Clone, Default)]
    pub struct FreezeAccountInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub mint: AccountMeta,

        pub token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for FreezeAccount instruction
    #[derive(Debug, Clone)]
    pub struct FreezeAccountInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub mint: Pubkey,

        pub token_account: Pubkey,
    }

    impl FreezeAccountInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey, mint: Pubkey, token_account: Pubkey) -> Self {
            Self {
                authority,

                config,

                mint,

                token_account,
            }
        }
    }

    /// Instruction data for FreezeAccount
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct FreezeAccountInstructionData {}

    impl FreezeAccountInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for FreezeAccountInstruction
    impl FreezeAccountInstruction {
        fn discriminator() -> [u8; 8] {
            [253u8, 75u8, 82u8, 133u8, 167u8, 238u8, 43u8, 130u8]
        }

        pub fn data(data: FreezeAccountInstructionData) -> Self {
            Self {
                accounts: FreezeAccountInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: FreezeAccountInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.token_account = AccountMeta::new(accounts.token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Initialize
    // ....................................................................

    /// Main instruction struct for Initialize
    pub struct InitializeInstruction {
        pub accounts: InitializeInstructionAccountMetas,
        pub data: InitializeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Initialize instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub mint: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for Initialize instruction
    #[derive(Debug, Clone)]
    pub struct InitializeInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub mint: Pubkey,

        pub token_program: Pubkey,
    }

    impl InitializeInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey, mint: Pubkey, token_program: Pubkey) -> Self {
            Self {
                authority,

                config,

                mint,

                token_program,
            }
        }
    }

    /// Instruction data for Initialize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeInstructionData {
        pub args: InitializeArgs,
    }

    impl InitializeInstructionData {
        pub fn new(args: InitializeArgs) -> Self {
            Self { args }
        }
    }

    /// Implementation for InitializeInstruction
    impl InitializeInstruction {
        fn discriminator() -> [u8; 8] {
            [175u8, 175u8, 109u8, 31u8, 13u8, 152u8, 155u8, 237u8]
        }

        pub fn data(data: InitializeInstructionData) -> Self {
            Self {
                accounts: InitializeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, true);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitializePermanentDelegate
    // ....................................................................

    /// Main instruction struct for InitializePermanentDelegate
    pub struct InitializePermanentDelegateInstruction {
        pub accounts: InitializePermanentDelegateInstructionAccountMetas,
        pub data: InitializePermanentDelegateInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializePermanentDelegate instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializePermanentDelegateInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub mint: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializePermanentDelegate instruction
    #[derive(Debug, Clone)]
    pub struct InitializePermanentDelegateInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub mint: Pubkey,

        pub token_program: Pubkey,
    }

    impl InitializePermanentDelegateInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey, mint: Pubkey, token_program: Pubkey) -> Self {
            Self {
                authority,

                config,

                mint,

                token_program,
            }
        }
    }

    /// Instruction data for InitializePermanentDelegate
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializePermanentDelegateInstructionData {
        pub args: InitializePermanentDelegateArgs,
    }

    impl InitializePermanentDelegateInstructionData {
        pub fn new(args: InitializePermanentDelegateArgs) -> Self {
            Self { args }
        }
    }

    /// Implementation for InitializePermanentDelegateInstruction
    impl InitializePermanentDelegateInstruction {
        fn discriminator() -> [u8; 8] {
            [98u8, 200u8, 9u8, 70u8, 17u8, 203u8, 130u8, 60u8]
        }

        pub fn data(data: InitializePermanentDelegateInstructionData) -> Self {
            Self {
                accounts: InitializePermanentDelegateInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(
            mut self,
            accounts: InitializePermanentDelegateInstructionAccounts,
        ) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, true);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitializeSss2
    // ....................................................................

    /// Main instruction struct for InitializeSss2
    pub struct InitializeSss2Instruction {
        pub accounts: InitializeSss2InstructionAccountMetas,
        pub data: InitializeSss2InstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeSss2 instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeSss2InstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub mint: AccountMeta,

        pub transfer_hook_program: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeSss2 instruction
    #[derive(Debug, Clone)]
    pub struct InitializeSss2InstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub mint: Pubkey,

        pub transfer_hook_program: Pubkey,

        pub token_program: Pubkey,
    }

    impl InitializeSss2InstructionAccounts {
        pub fn new(
            authority: Pubkey,

            config: Pubkey,

            mint: Pubkey,

            transfer_hook_program: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                authority,

                config,

                mint,

                transfer_hook_program,

                token_program,
            }
        }
    }

    /// Instruction data for InitializeSss2
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeSss2InstructionData {
        pub args: InitializeSss2Args,
    }

    impl InitializeSss2InstructionData {
        pub fn new(args: InitializeSss2Args) -> Self {
            Self { args }
        }
    }

    /// Implementation for InitializeSss2Instruction
    impl InitializeSss2Instruction {
        fn discriminator() -> [u8; 8] {
            [55u8, 253u8, 209u8, 103u8, 146u8, 222u8, 48u8, 2u8]
        }

        pub fn data(data: InitializeSss2InstructionData) -> Self {
            Self {
                accounts: InitializeSss2InstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeSss2InstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, true);

            self.accounts.transfer_hook_program =
                AccountMeta::new_readonly(accounts.transfer_hook_program, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.transfer_hook_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Mint
    // ....................................................................

    /// Main instruction struct for Mint
    pub struct MintInstruction {
        pub accounts: MintInstructionAccountMetas,
        pub data: MintInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Mint instruction
    #[derive(Debug, Clone, Default)]
    pub struct MintInstructionAccountMetas {
        pub minter: AccountMeta,

        pub config: AccountMeta,

        pub role_account: AccountMeta,

        pub minter_quota: AccountMeta,

        pub mint: AccountMeta,

        pub recipient_token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Mint instruction
    #[derive(Debug, Clone)]
    pub struct MintInstructionAccounts {
        pub minter: Pubkey,

        pub config: Pubkey,

        pub role_account: Pubkey,

        pub minter_quota: Pubkey,

        pub mint: Pubkey,

        pub recipient_token_account: Pubkey,

        pub token_program: Pubkey,
    }

    impl MintInstructionAccounts {
        pub fn new(
            minter: Pubkey,

            config: Pubkey,

            role_account: Pubkey,

            minter_quota: Pubkey,

            mint: Pubkey,

            recipient_token_account: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                minter,

                config,

                role_account,

                minter_quota,

                mint,

                recipient_token_account,

                token_program,
            }
        }
    }

    /// Instruction data for Mint
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct MintInstructionData {
        pub amount: u64,
    }

    impl MintInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for MintInstruction
    impl MintInstruction {
        fn discriminator() -> [u8; 8] {
            [51u8, 57u8, 225u8, 47u8, 182u8, 146u8, 137u8, 166u8]
        }

        pub fn data(data: MintInstructionData) -> Self {
            Self {
                accounts: MintInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: MintInstructionAccounts) -> Self {
            self.accounts.minter = AccountMeta::new(accounts.minter, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.role_account = AccountMeta::new_readonly(accounts.role_account, false);

            self.accounts.minter_quota = AccountMeta::new(accounts.minter_quota, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.recipient_token_account =
                AccountMeta::new(accounts.recipient_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.minter.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_account.clone());

            metas.push(self.accounts.minter_quota.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.recipient_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Pause
    // ....................................................................

    /// Main instruction struct for Pause
    pub struct PauseInstruction {
        pub accounts: PauseInstructionAccountMetas,
        pub data: PauseInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Pause instruction
    #[derive(Debug, Clone, Default)]
    pub struct PauseInstructionAccountMetas {
        pub pauser: AccountMeta,

        pub config: AccountMeta,

        pub role_account: AccountMeta,
    }

    /// Account pubkeys for Pause instruction
    #[derive(Debug, Clone)]
    pub struct PauseInstructionAccounts {
        pub pauser: Pubkey,

        pub config: Pubkey,

        pub role_account: Pubkey,
    }

    impl PauseInstructionAccounts {
        pub fn new(pauser: Pubkey, config: Pubkey, role_account: Pubkey) -> Self {
            Self {
                pauser,

                config,

                role_account,
            }
        }
    }

    /// Instruction data for Pause
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct PauseInstructionData {}

    impl PauseInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for PauseInstruction
    impl PauseInstruction {
        fn discriminator() -> [u8; 8] {
            [211u8, 22u8, 221u8, 251u8, 74u8, 121u8, 193u8, 47u8]
        }

        pub fn data(data: PauseInstructionData) -> Self {
            Self {
                accounts: PauseInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: PauseInstructionAccounts) -> Self {
            self.accounts.pauser = AccountMeta::new_readonly(accounts.pauser, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.role_account = AccountMeta::new_readonly(accounts.role_account, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.pauser.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_account.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RemoveFromBlacklist
    // ....................................................................

    /// Main instruction struct for RemoveFromBlacklist
    pub struct RemoveFromBlacklistInstruction {
        pub accounts: RemoveFromBlacklistInstructionAccountMetas,
        pub data: RemoveFromBlacklistInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RemoveFromBlacklist instruction
    #[derive(Debug, Clone, Default)]
    pub struct RemoveFromBlacklistInstructionAccountMetas {
        pub blacklister: AccountMeta,

        pub config: AccountMeta,

        pub role_account: AccountMeta,

        pub address_to_remove: AccountMeta,

        pub blacklist_entry: AccountMeta,
    }

    /// Account pubkeys for RemoveFromBlacklist instruction
    #[derive(Debug, Clone)]
    pub struct RemoveFromBlacklistInstructionAccounts {
        pub blacklister: Pubkey,

        pub config: Pubkey,

        pub role_account: Pubkey,

        pub address_to_remove: Pubkey,

        pub blacklist_entry: Pubkey,
    }

    impl RemoveFromBlacklistInstructionAccounts {
        pub fn new(
            blacklister: Pubkey,

            config: Pubkey,

            role_account: Pubkey,

            address_to_remove: Pubkey,

            blacklist_entry: Pubkey,
        ) -> Self {
            Self {
                blacklister,

                config,

                role_account,

                address_to_remove,

                blacklist_entry,
            }
        }
    }

    /// Instruction data for RemoveFromBlacklist
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RemoveFromBlacklistInstructionData {}

    impl RemoveFromBlacklistInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for RemoveFromBlacklistInstruction
    impl RemoveFromBlacklistInstruction {
        fn discriminator() -> [u8; 8] {
            [47u8, 105u8, 20u8, 10u8, 165u8, 168u8, 203u8, 219u8]
        }

        pub fn data(data: RemoveFromBlacklistInstructionData) -> Self {
            Self {
                accounts: RemoveFromBlacklistInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RemoveFromBlacklistInstructionAccounts) -> Self {
            self.accounts.blacklister = AccountMeta::new(accounts.blacklister, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.role_account = AccountMeta::new_readonly(accounts.role_account, false);

            self.accounts.address_to_remove =
                AccountMeta::new_readonly(accounts.address_to_remove, false);

            self.accounts.blacklist_entry = AccountMeta::new(accounts.blacklist_entry, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.blacklister.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_account.clone());

            metas.push(self.accounts.address_to_remove.clone());

            metas.push(self.accounts.blacklist_entry.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Seize
    // ....................................................................

    /// Main instruction struct for Seize
    pub struct SeizeInstruction {
        pub accounts: SeizeInstructionAccountMetas,
        pub data: SeizeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Seize instruction
    #[derive(Debug, Clone, Default)]
    pub struct SeizeInstructionAccountMetas {
        pub seizer: AccountMeta,

        pub config: AccountMeta,

        pub role_account: AccountMeta,

        pub mint: AccountMeta,

        pub source_token_account: AccountMeta,

        pub treasury_token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Seize instruction
    #[derive(Debug, Clone)]
    pub struct SeizeInstructionAccounts {
        pub seizer: Pubkey,

        pub config: Pubkey,

        pub role_account: Pubkey,

        pub mint: Pubkey,

        pub source_token_account: Pubkey,

        pub treasury_token_account: Pubkey,

        pub token_program: Pubkey,
    }

    impl SeizeInstructionAccounts {
        pub fn new(
            seizer: Pubkey,

            config: Pubkey,

            role_account: Pubkey,

            mint: Pubkey,

            source_token_account: Pubkey,

            treasury_token_account: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                seizer,

                config,

                role_account,

                mint,

                source_token_account,

                treasury_token_account,

                token_program,
            }
        }
    }

    /// Instruction data for Seize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SeizeInstructionData {
        pub amount: u64,
    }

    impl SeizeInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for SeizeInstruction
    impl SeizeInstruction {
        fn discriminator() -> [u8; 8] {
            [129u8, 159u8, 143u8, 31u8, 161u8, 224u8, 241u8, 84u8]
        }

        pub fn data(data: SeizeInstructionData) -> Self {
            Self {
                accounts: SeizeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SeizeInstructionAccounts) -> Self {
            self.accounts.seizer = AccountMeta::new_readonly(accounts.seizer, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.role_account = AccountMeta::new_readonly(accounts.role_account, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.source_token_account =
                AccountMeta::new(accounts.source_token_account, false);

            self.accounts.treasury_token_account =
                AccountMeta::new(accounts.treasury_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.seizer.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_account.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.source_token_account.clone());

            metas.push(self.accounts.treasury_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ThawAccount
    // ....................................................................

    /// Main instruction struct for ThawAccount
    pub struct ThawAccountInstruction {
        pub accounts: ThawAccountInstructionAccountMetas,
        pub data: ThawAccountInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ThawAccount instruction
    #[derive(Debug, Clone, Default)]
    pub struct ThawAccountInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub mint: AccountMeta,

        pub token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for ThawAccount instruction
    #[derive(Debug, Clone)]
    pub struct ThawAccountInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub mint: Pubkey,

        pub token_account: Pubkey,
    }

    impl ThawAccountInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey, mint: Pubkey, token_account: Pubkey) -> Self {
            Self {
                authority,

                config,

                mint,

                token_account,
            }
        }
    }

    /// Instruction data for ThawAccount
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ThawAccountInstructionData {}

    impl ThawAccountInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ThawAccountInstruction
    impl ThawAccountInstruction {
        fn discriminator() -> [u8; 8] {
            [115u8, 152u8, 79u8, 213u8, 213u8, 169u8, 184u8, 35u8]
        }

        pub fn data(data: ThawAccountInstructionData) -> Self {
            Self {
                accounts: ThawAccountInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ThawAccountInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.token_account = AccountMeta::new(accounts.token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: TransferAuthority
    // ....................................................................

    /// Main instruction struct for TransferAuthority
    pub struct TransferAuthorityInstruction {
        pub accounts: TransferAuthorityInstructionAccountMetas,
        pub data: TransferAuthorityInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for TransferAuthority instruction
    #[derive(Debug, Clone, Default)]
    pub struct TransferAuthorityInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub new_authority: AccountMeta,
    }

    /// Account pubkeys for TransferAuthority instruction
    #[derive(Debug, Clone)]
    pub struct TransferAuthorityInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub new_authority: Pubkey,
    }

    impl TransferAuthorityInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey, new_authority: Pubkey) -> Self {
            Self {
                authority,

                config,

                new_authority,
            }
        }
    }

    /// Instruction data for TransferAuthority
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct TransferAuthorityInstructionData {}

    impl TransferAuthorityInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for TransferAuthorityInstruction
    impl TransferAuthorityInstruction {
        fn discriminator() -> [u8; 8] {
            [48u8, 169u8, 76u8, 72u8, 229u8, 180u8, 55u8, 161u8]
        }

        pub fn data(data: TransferAuthorityInstructionData) -> Self {
            Self {
                accounts: TransferAuthorityInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: TransferAuthorityInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.new_authority = AccountMeta::new_readonly(accounts.new_authority, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.new_authority.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Unpause
    // ....................................................................

    /// Main instruction struct for Unpause
    pub struct UnpauseInstruction {
        pub accounts: UnpauseInstructionAccountMetas,
        pub data: UnpauseInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Unpause instruction
    #[derive(Debug, Clone, Default)]
    pub struct UnpauseInstructionAccountMetas {
        pub pauser: AccountMeta,

        pub config: AccountMeta,

        pub role_account: AccountMeta,
    }

    /// Account pubkeys for Unpause instruction
    #[derive(Debug, Clone)]
    pub struct UnpauseInstructionAccounts {
        pub pauser: Pubkey,

        pub config: Pubkey,

        pub role_account: Pubkey,
    }

    impl UnpauseInstructionAccounts {
        pub fn new(pauser: Pubkey, config: Pubkey, role_account: Pubkey) -> Self {
            Self {
                pauser,

                config,

                role_account,
            }
        }
    }

    /// Instruction data for Unpause
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UnpauseInstructionData {}

    impl UnpauseInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for UnpauseInstruction
    impl UnpauseInstruction {
        fn discriminator() -> [u8; 8] {
            [169u8, 144u8, 4u8, 38u8, 10u8, 141u8, 188u8, 255u8]
        }

        pub fn data(data: UnpauseInstructionData) -> Self {
            Self {
                accounts: UnpauseInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UnpauseInstructionAccounts) -> Self {
            self.accounts.pauser = AccountMeta::new_readonly(accounts.pauser, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.role_account = AccountMeta::new_readonly(accounts.role_account, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.pauser.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_account.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateMinter
    // ....................................................................

    /// Main instruction struct for UpdateMinter
    pub struct UpdateMinterInstruction {
        pub accounts: UpdateMinterInstructionAccountMetas,
        pub data: UpdateMinterInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateMinter instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateMinterInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub minter: AccountMeta,

        pub role_account: AccountMeta,

        pub minter_quota: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for UpdateMinter instruction
    #[derive(Debug, Clone)]
    pub struct UpdateMinterInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub minter: Pubkey,

        pub role_account: Pubkey,

        pub minter_quota: Pubkey,
    }

    impl UpdateMinterInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            config: Pubkey,

            minter: Pubkey,

            role_account: Pubkey,

            minter_quota: Pubkey,
        ) -> Self {
            Self {
                authority,

                config,

                minter,

                role_account,

                minter_quota,
            }
        }
    }

    /// Instruction data for UpdateMinter
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateMinterInstructionData {
        pub is_active: bool,

        pub quota_limit: u64,
    }

    impl UpdateMinterInstructionData {
        pub fn new(is_active: bool, quota_limit: u64) -> Self {
            Self {
                is_active,

                quota_limit,
            }
        }
    }

    /// Implementation for UpdateMinterInstruction
    impl UpdateMinterInstruction {
        fn discriminator() -> [u8; 8] {
            [164u8, 129u8, 164u8, 88u8, 75u8, 29u8, 91u8, 38u8]
        }

        pub fn data(data: UpdateMinterInstructionData) -> Self {
            Self {
                accounts: UpdateMinterInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateMinterInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.minter = AccountMeta::new_readonly(accounts.minter, false);

            self.accounts.role_account = AccountMeta::new(accounts.role_account, false);

            self.accounts.minter_quota = AccountMeta::new(accounts.minter_quota, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.minter.clone());

            metas.push(self.accounts.role_account.clone());

            metas.push(self.accounts.minter_quota.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateRoles
    // ....................................................................

    /// Main instruction struct for UpdateRoles
    pub struct UpdateRolesInstruction {
        pub accounts: UpdateRolesInstructionAccountMetas,
        pub data: UpdateRolesInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateRoles instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateRolesInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub assignee: AccountMeta,

        pub role_account: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for UpdateRoles instruction
    #[derive(Debug, Clone)]
    pub struct UpdateRolesInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub assignee: Pubkey,

        pub role_account: Pubkey,
    }

    impl UpdateRolesInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            config: Pubkey,

            assignee: Pubkey,

            role_account: Pubkey,
        ) -> Self {
            Self {
                authority,

                config,

                assignee,

                role_account,
            }
        }
    }

    /// Instruction data for UpdateRoles
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateRolesInstructionData {
        pub args: UpdateRolesArgs,
    }

    impl UpdateRolesInstructionData {
        pub fn new(args: UpdateRolesArgs) -> Self {
            Self { args }
        }
    }

    /// Implementation for UpdateRolesInstruction
    impl UpdateRolesInstruction {
        fn discriminator() -> [u8; 8] {
            [220u8, 152u8, 205u8, 233u8, 177u8, 123u8, 219u8, 125u8]
        }

        pub fn data(data: UpdateRolesInstructionData) -> Self {
            Self {
                accounts: UpdateRolesInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateRolesInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.assignee = AccountMeta::new_readonly(accounts.assignee, false);

            self.accounts.role_account = AccountMeta::new(accounts.role_account, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.assignee.clone());

            metas.push(self.accounts.role_account.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: BlacklistEntry
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct BlacklistEntry {
    pub mint: Pubkey,

    pub blacklisted_address: Pubkey,

    pub bump: u8,
}

impl BlacklistEntry {
    pub fn new(mint: Pubkey, blacklisted_address: Pubkey, bump: u8) -> Self {
        Self {
            mint,

            blacklisted_address,

            bump,
        }
    }
}

/// Custom struct: InitializeArgs
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct InitializeArgs {
    pub name: String,

    pub symbol: String,

    pub uri: String,

    pub decimals: u8,
}

impl InitializeArgs {
    pub fn new(name: String, symbol: String, uri: String, decimals: u8) -> Self {
        Self {
            name,

            symbol,

            uri,

            decimals,
        }
    }
}

/// Custom struct: InitializePermanentDelegateArgs
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct InitializePermanentDelegateArgs {
    pub name: String,

    pub symbol: String,

    pub uri: String,

    pub decimals: u8,
}

impl InitializePermanentDelegateArgs {
    pub fn new(name: String, symbol: String, uri: String, decimals: u8) -> Self {
        Self {
            name,

            symbol,

            uri,

            decimals,
        }
    }
}

/// Custom struct: InitializeSss2Args
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct InitializeSss2Args {
    pub name: String,

    pub symbol: String,

    pub uri: String,

    pub decimals: u8,
}

impl InitializeSss2Args {
    pub fn new(name: String, symbol: String, uri: String, decimals: u8) -> Self {
        Self {
            name,

            symbol,

            uri,

            decimals,
        }
    }
}

/// Custom struct: MinterQuota
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MinterQuota {
    pub mint: Pubkey,

    pub minter: Pubkey,

    pub quota_limit: u64,

    pub minted_amount: u64,

    pub bump: u8,
}

impl MinterQuota {
    pub fn new(
        mint: Pubkey,

        minter: Pubkey,

        quota_limit: u64,

        minted_amount: u64,

        bump: u8,
    ) -> Self {
        Self {
            mint,

            minter,

            quota_limit,

            minted_amount,

            bump,
        }
    }
}

/// Custom struct: RoleAccount
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct RoleAccount {
    pub mint: Pubkey,

    pub assignee: Pubkey,

    pub role_type: RoleType,

    pub is_active: bool,

    pub bump: u8,
}

impl RoleAccount {
    pub fn new(
        mint: Pubkey,

        assignee: Pubkey,

        role_type: RoleType,

        is_active: bool,

        bump: u8,
    ) -> Self {
        Self {
            mint,

            assignee,

            role_type,

            is_active,

            bump,
        }
    }
}

/// Custom enum: RoleType
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub enum RoleType {
    Minter,

    Burner,

    Pauser,

    Blacklister,

    Seizer,
}

/// Custom struct: StablecoinConfig
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct StablecoinConfig {
    pub mint: Pubkey,

    pub master_authority: Pubkey,

    pub decimals: u8,

    pub is_paused: bool,

    pub enable_permanent_delegate: bool,

    pub enable_transfer_hook: bool,

    pub bump: u8,
}

impl StablecoinConfig {
    pub fn new(
        mint: Pubkey,

        master_authority: Pubkey,

        decimals: u8,

        is_paused: bool,

        enable_permanent_delegate: bool,

        enable_transfer_hook: bool,

        bump: u8,
    ) -> Self {
        Self {
            mint,

            master_authority,

            decimals,

            is_paused,

            enable_permanent_delegate,

            enable_transfer_hook,

            bump,
        }
    }
}

/// Custom struct: UpdateRolesArgs
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct UpdateRolesArgs {
    pub role_type: RoleType,

    pub is_active: bool,
}

impl UpdateRolesArgs {
    pub fn new(role_type: RoleType, is_active: bool) -> Self {
        Self {
            role_type,

            is_active,
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
